$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        550:{
            items:2
        },
        700:{
            items:3
        },
        950:{
            items:4
        },
        1200:{
            items:5
        }
    }
})